### PR TITLE
TS, Prettier, Eslint

### PR DESCRIPTION
**Pull request by nanot1m**
Related to #34, #35 

- rewrote index.js to typescript
  - ~~mocked typings for **roughjs** as `any`~~ rough is written in TS
  - restructured **App** component for better type inference
- pre-commit hook with prettier and eslint
  - default prettier config
  - react-app config for eslint (as it was already installed)

It is a little bit tricky to type elements array, which is patching by `generateDraw` function later.
Maybe we should create an abstract class for `ExcaliburElement` and extend it for every other type of elements?

### CODE REVIEW

**Comment by dwelle** [comment]
> mocked typings for roughjs as any

Isn't [roughjs](https://github.com/pshihn/rough) written in TS?

**Comment by nanot1m** [comment]
> Isn't roughjs written in TS?

😮 Did not know that... Thanks!

**Comment by nanot1m** [comment]
Reused type definition for rough from the rough package.

**Comment by vjeux** [comment]
Looks like `?.` needs to be enabled for it to work in codesandbox: https://codesandbox.io/s/github/excalidraw/excalibur

```js
/src/index.tsx: Support for the experimental syntax 'optionalChaining' isn't currently enabled (288:37):

  286 |       event.key === "Backspace" 
  287 |       &&
> 288 |        (event.target as HTMLElement)?.nodeName !== "INPUT"
      |                                     ^
  289 |     ) {
  290 |       for (var i = elements.length - 1; i >= 0; --i) {
  291 |         if (elements[i].isSelected) {

Add @babel/plugin-proposal-optional-chaining (https://git.io/vb4Sk) to the 'plugins' section of your Babel config to enable transformation.

  286 |       event.key === "Backspace" 
  287 |       &&
> 288 |        (event.target as HTMLElement)?.nodeName !== "INPUT"
      |                                     ^
  289 |     ) {
  290 |       for (var i = elements.length - 1; i >= 0; --i) {
  291 |         if (elements[i].isSelected) {
```

**Comment by dwelle** [comment]
@vjeux Yes, but CRA (i.e. `react-scripts`) won't let us do that, right?

**Comment by vjeux** [comment]
That's not encouraging, he's basically forking react-scripts to allow overrides...
https://medium.com/@adostes/enabling-optional-chaining-in-a-create-react-app-a9f626a515d9

**Comment by dwelle** [comment]
But according to this PR (https://github.com/facebook/create-react-app/pull/7438), react-scripts should already support that :thinking:

**Comment by vjeux** [comment]
This was merged November 8 and the latest published version is 3.3.0 (which is the one we're using) on December 4. Not sure what's going on

**Comment by dwelle** [comment]
I've [asked for help](https://spectrum.chat/codesandbox/help/cra-ts-optional-chaining~aa7abc8d-2e76-43e2-b5a6-9e90cd38eab9). In the meantime, I'd not use optional chaining. IMO in this specific case we don't even need to (`target` is pretty much guaranteed to be a DOM node, and TS doesn't even complain).

**Comment by vjeux** [comment]
Yeah, let's remove it for now :)

I'm having an issue since I moved to the organization, codesandbox won't let me create commits or send PRs :( sadpanda

**Comment by dwelle** [comment]
Yea, I don't have access either, but I thought you'd have to give me access on CodeSandbox, separately. I guess the problem is elsewhere, then.

**Comment by vjeux** [comment]
@CompuIves is working a fix for codesandbox as we speak

**Comment by dwelle** [comment]
I'll make the fix nevertheless.

**Comment by vjeux** [comment]
Okay, we figured it out, need to manually grant permission to "excalidraw" org here: https://github.com/settings/connections/applications/c07a89833b557afc7be2

He is going to update the UI to ask for more permissions when needed, but in the meantime that should get you unblocked.

**Pull request merged**
