### PR TITLE
Add Text Colors

### PR DESCRIPTION
**Pull request by Fausto95**
Since we can already choose colors for the shapes, I think it'd be cool to make it possible to pick a color for the text too.

Capture d’écran 2020-01-03 à 17 15 04

Actually, this should be introduced by https://github.com/excalidraw/excalibur/pull/54

### CODE REVIEW

**Comment by Fausto95** [comment]
> Should we use strokeColor for it?

Yes, I think that works too!

**Comment by Fausto95** [comment]
I just committed a veersion using strookeColor @vjeux

**Comment by Fausto95** [comment]
> You need to store the previous fillStyle in a variable and revert it after you call fillText. Otherwise it’s going to change the color of all the subsequent canvas operations :(

Oh yeah, I completely missed that, thanks!

**Comment by Fausto95** [comment]
Done @vjeux

**Comment by vjeux** [comment]
Thanks for contributing! I just added you as a contributor to the repo :)

**Comment by Fausto95** [comment]
> Thanks for contributing! I just added you as a contributor to the repo :)

Thanks :)

**Pull request merged**
